### PR TITLE
feat: :sparkles: Allow package to be required

### PR DESCRIPTION
**Pull request by cadesalaberry**

### CODE REVIEW

**Comment by dwmkerr** [comment]
This is excellent, thanks @cadesalaberry! Do you think you could add a note to the `README` on how to use the package programatically?

**Comment by cadesalaberry** [comment]
With pleasure.

**Comment by dwmkerr** [comment]
This is awesome, thanks @cadesalaberry!

**Comment by dwmkerr** [comment]
I've just added a note to the changelog thanking you and will publish shortly!

**Pull request merged**
